---
# install collections required
collections:
  - name: ansible.netcommon
    source: https://galaxy.ansible.com
  - name: arubanetworks.aos_switch
    source: https://galaxy.ansible.com
  - name: arubanetworks.aoscx
    source: https://galaxy.ansible.com
