---
- name: STP
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name: STP
      aoscx_config:
        lines:
          - spanning-tree mode rpvst


- name: Root_Priority
  hosts: WFM_FHC_MDF_CORE1
  collections:
      - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name:
      aoscx_config:
        lines:
          - spanning-tree priority 1

- name: BPDU_Guard
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name: BPDUGUARD
      aoscx_config:
        lines:
          - spanning-tree bpdu-guard
        parents:
          - interface 1/1/1-1/1/48
          - interface 2/1/1-2/1/48
        match: none
