---
- name: STP
  hosts: acx_switch
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
  - name: STP
    aoscx_config:
      lines:
        - spanning-tree mode rapid-pvst
    save_when: always
