---
- name: VLAN
  hosts: MAIN
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: VLAN 2
      aoscx_vlan:
        vlan_id: 2
        name: Mgmt
    - name: VLAN 5
      aoscx_vlan:
        vlan_id: 5
        name: Epic_Storage
    - name: VLAN 8
      aoscx_vlan:
        vlan_id: 8
        name: Data
    - name: VLAN 10
      aoscx_vlan:
        vlan_id: 10
        name: HTCHC-DATA
    - name: VLAN 14
      aoscx_vlan:
        vlan_id: 14
        name: VOIP
    - name: VLAN20
      aoscx_vlan:
        vlan_id: 20
        name: Legacy-Data
    - name: VLAN 24
      aoscx_vlan:
        vlan_id: 24
        name: WLAN-Staff
    - name: VLAN 28
      aoscx_vlan:
        vlan_id: 28
        name: WLAN-Guest
    - name: VLAN 30
      aoscx_vlan:
        vlan_id: 30
        name: HTCHC-WIRELESS
    - name: VLAN 32
      aoscx_vlan:
        vlan_id: 32
        name: WLAN-BYOD
    - name: VLAN 40
      aoscx_vlan:
        vlan_id: 40
        name: WifiPhone
    - name: VLAN 50
      aoscx_vlan:
        vlan_id: 50
        name: DMZ
    - name: VLAN 60
      aoscx_vlan:
        vlan_id: 60
        name: Citrix
    - name: VLAN 65
      aoscx_vlan:
        vlan_id: 65
        name: CitrixTST
    - name: VLAN 70
      aoscx_vlan:
        vlan_id: 70
        name: MadCoop
    - name: VLAN 75
      aoscx_vlan:
        vlan_id: 75
        name: LAB
    - name: VLAN 100
      aoscx_vlan:
        vlan_id: 100
        name: Printers
    - name: VLAN 102
      aoscx_vlan:
        vlan_id: 102
        name: IoT
    - name: VLAN 202
      aoscx_vlan:
        vlan_id: 202
        name: AP-Mgmt
    - name: VLAN 500
      aoscx_vlan:
        vlan_id: 500
        name: HTCHC-Native
    - name: VLAN 1000
      aoscx_vlan:
        vlan_id: 1000
        name: ELAN
    - name: VLAN 1001
      aoscx_vlan:
        vlan_id: 1001
        name: Madison-Cooper-WAN
    - name: VLAN 2000
      aoscx_vlan:
        vlan_id: 2000
        name: SDWAN-TRANS
