---
- name: STP
  hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name: STP
      aoscx_config:
        lines:
          - spanning-tree mode rpvst


- name: Root_Priority
  hosts: MDF
  collections:
      - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name:
      aoscx_config:
        lines:
          - spanning-tree priority 1

- name: BPDU_Guard
  hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name:
      aoscx_config:
        lines:
          - spanning-tree bpdu-guard
        parents:
          - interface 1/1/1-1/1/48
        match:
          - none
