---
- name: STP
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name: STP
      aoscx_config:
        lines:
          - spanning-tree mode rpvst


- name: Root_Priority
  hosts: WFM_FHC_MDF_CORE1
  collections:
      - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name:
      aoscx_config:
        lines:
          - spanning-tree priority 1

- name: BPDU_Guard
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name: BPDUGUARD
      aoscx_config:
        lines:
          - spanning-tree bpdu-guard
        parents:
          - interface 2/1/1-2/1/48
          - interface 3/1/1-3/1/48
          - interface 4/1/1-4/1/48
          - interface 5/1/1-5/1/48
          - interface 6/1/1-6/1/48
          - interface 7/1/1-7/1/48
        match: none
