---
- name: STP
  hosts: WACO
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
  - name: STP
    aoscx_config:
      lines:
        - spanning-tree mode rpvst


- name: Root_Priority
    hosts: MDF
    collections:
      - arubanetworks.aoscx
    vars:
      - ansible_connection: network_cli
    tasks:
    - name:
      aoscx_config:
        lines:
          - spanning-tree priority 1
