- name: DEVICE SPECIFIC
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: SVI'S
      aoscx_vlan_interface:
        vlan_id: "{{ item.id }}"
        description: "{{ item.svi_des }}"
        ipv4: "{{ item.ip_add }}"
      loop:
        - { id: '1', ip_add: '10.133.1.1', svi_des: 'Legacy-Data' }
        - { id: '2', ip_add: '10.101.2.1', svi_des: 'Mgmt' }
        - { id: '5', ip_add: ' ', svi_des: 'Epic_Storage' }
        - { id: '8', ip_add: '10.101.8.1', svi_des: 'Data' }
        - { id: '10', ip_add: ' ', svi_des: 'HTCHC-DATA' }
        - { id: '14', ip_add: '10.101.14.1', svi_des: 'VOIP' }
        - { id: '20', ip_add: '10.133.1.1', svi_des: 'HTCHC-VOICE' }
        - { id: '24', ip_add: '10.101.24.1', svi_des: 'WLAN-Staff' }
        - { id: '28', ip_add: '10.101.28.1', svi_des: 'WLAN-Guest' }
        - { id: '30', ip_add: '10.132.101.1', svi_des: 'HTCHC-WIRELESS' }
        - { id: '32', ip_add: '10.101.32.1', svi_des: 'WLAN-BYOD' }
        - { id: '40', ip_add: ' ', svi_des: 'WifiPhone' }
        - { id: '50', ip_add: ' ', svi_des: 'DMZ' }
        - { id: '60', ip_add: '10.132.52.1', svi_des: 'Citrix' }
        - { id: '65', ip_add: '10.132.53.1', svi_des: 'CitrixTST' }
        - { id: '70', ip_add: '10.132.6.1', svi_des: 'MadCoop' }
        - { id: '75', ip_add: '10.101.75.1, 10.132.6.1', svi_des: 'Lab' }
        - { id: '100', ip_add: '10.101.100.1', svi_des: 'Printers' }
        - { id: '102', ip_add: '10.101.102.1', svi_des: 'IoT' }
        - { id: '202', ip_add: '10.101.102.1', svi_des: 'AP-Mgmt' }
        - { id: '500', ip_add: ' ', svi_des: 'HTCHC-Native' }
        - { id: '1000', ip_add: '192.168.99.1', svi_des: 'ELAN' }
        - { id: '1001', ip_add: '10.255.255.69', svi_des: 'Madison Cooper WAN' }
        - { id: '2000', ip_add: '10.255.255.249', svi_des: 'SDWAN-TRANS' }
