- name: DEVICE SPECIFIC
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Create VLAN Interface 100
      aoscx_vlan_interface:
        vlan_id: 100
        description: UPLINK_VLAN
        ipv4: ['10.10.20.1/24']
    
