- name: GATHER_FACTS
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  tasks:
    - name: Retrieve all information from the device and save into a variable "facts_output"
      aoscx_facts:
        gather_subset: ['power_supplies', 'domain_name']
      register: facts_output
