---
- name: Upgrade IOS
  hosts: Cat3750
  vars: 
    upgrade_ios_version: 150-2.SE11
  tasks: 
  - name: Verify current version
    ios_facts:
  - debug:
      msg:
      - "Current version is {{ ansible_net_version }}"
      - "Upgrade image is 150-2.SE11"
  - debug:
      msg:
      - "Image is not compliant and will be upgrade"
    when: ansible_net_version != upgrade_ios_version

- hosts: localhost
  tasks:
  - name: Get ansible Date/time facts
    setup:
      filter: "ansible_date_time"
      gather_subset: "!all"
  - name: Store DTG as fact
    set_fact:
      DTG: "{{ ansible_date_time.date }}"
- hosts: Cat3750
  tasks:
  - name: Backup running config
    ios_command:
      commands: show run
    register: config
  - name: Save to bakcup
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "/home/traversa/automation/backup/{{ hostvars.localhost.DTG }}/{{ inventory_hostname }}-{{ hostvars.localhost.DTG }}-config.txt"
  - name: Save running config
    ios_config:
      save_when: always

  - name: Copy image
    net_put:
      src: "/home/traversa/image/c3750-ipbasek9-mz.150-2.SE11.bin"
      dest: "flash:c3750-ipbasek9-mz.150-2.SE11.bin"
    vars:
      ansible_command_timeout: 600
  - name: Change Boot variable to new image
    ios_config:
      commands:
        - "boot system flash:c3750-ipbasek9-mz.150-2.SE11.bin"
      save_when: always
  - name: Reload
    cli_command:
      command: reload
      prompt:
        - comfirm
      answer:
        - 'y'
  - name: Wait come back online
    wait_for:
      host: "{{ ansible_hostname }}"
      port: 22
      delay: 60
      timeout: 900
    delegate_to: localhost
  - name: Check Image version
    ios_facts:
  - debug:
      msg:
      - "current version is {{ ansible_net_version }}"
  - name: Assert OS version is correct
    vars:
      upgrade_ios_version: 150-2.SE11
    assert:
      that:
      - upgrade_ios_version == ansible_net_version
  - debug:
      msg:
      - "Software upgrade successfully"

