---
- name: UsernamePassword
  hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
    - name: UsernamePassword
      aoscx_config:
        lines:
          -  user admin group administrators password plaintext Pr0curve
