---
- name: Spanning Tree
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  tasks:
  - name: Enabling Spanning Tree
    aoscx_config:
      lines:
        - configure terminal
        - spanning-tree
        - exit
  - name: Spanning Tree Priority
    hosts: WFM_FHC_MDF_CORE2
    aoscx_config:
      lines: ['spanning-tree priority 1','exit']
        
