---
- name: Spanning Tree
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  
  tasks:
  - name: Enabling Spanning Tree
    aoscx_config:
      lines:
        - spanning-tree
      diff_against: running
      
  - name: Spanning Tree Priority
    aoscx_config:
      lines: ['spanning-tree priority 1']
    when: ansible_host == '10.210.210.11'
 
  - name: Enabling BPDU-GUARD
    aoscx_l2_interface:
      interface: 1/1/1
      admin_state: down
      description: testing ansible
