---
- name: Spanning Tree
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  
  tasks:
  - name: Enabling Spanning Tree
    aoscx_config:
      lines:
        - spanning-tree
      diff_against: running
      
  - name: Spanning Tree Priority
    aoscx_config:
      lines: ['spanning-tree priority 1']
    when: ansible_host == '10.210.210.11'

  - name: L2 Vlans -> Main Campus
    aoscx_vlan:
      vlan_id: 2
      name: Legacy-Data
