---
- name: Spanning Tree
  hosts: WFM_FHC_MDF_CORE1
  collections:
    - arubanetworks.aoscx
  vars:
    - ansible_connection: network_cli
  
  tasks:
  - name: Enabling Spanning Tree
    aoscx_config:
      lines:
        - spanning-tree
      diff_against: running
      
  - name: Spanning Tree Priority
    aoscx_config:
      lines: ['spanning-tree priority 1']
    when: ansible_host == '10.210.210.11'

  - name: Create VLAN 300 with description and name
    aoscx_vlan:
      vlan_id: 300
      name: UPLINK_VLAN
      description: This is VLAN 300
